# This is a basic workflow to help you get started with Actions

name: UpdateMessage

# Controls when the workflow will run
on:
  schedule:
    - cron: "05 5,15 * * *" #runs at 15:05 UTC everyday

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run update py
        run: /usr/bin/python3 log_generator.py
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.MY_TOKEN }}
